### ISSUE TITLE
Views not updating for containers added after other components.

### ISSUE THREAD

**Issue by ryanpcmcquen** [DeloitteDigitalAPAC/react-habitat-redux#8]
Here's how to reproduce the bug:

- Head here: https://ryanpcmcquen.org/react-habitat-poc/
- Click _ADD TO CART_ (it works).
- Edit the HTML for the page in the dev tools, add in a container like this:
```html
<div data-component="Cart"></div>
```
- Run `window.updateHabitat();` in the console to make the new `Cart` appear.
- Edit the HTML again for the page in the dev tools, add in a container like this:
```html
<div
    data-component="ProductCard"
    data-prop-add-to-cart="true"
    data-prop-alt="Teakhaus Edge Grain cutting board"
    data-prop-price="$200.00"
    data-prop-sku="3422086"
></div>
```
- Run `window.updateHabitat();` in the console to make the new `ProductCard` appear.
- Now click _ADD TO CART_ on the new `ProductCard` container.
- Although the Redux state updates (as seen in the Redux dev tools), the `Cart` view does not update, as seen by the lack of the number incrementing.

Source: https://github.com/ryanpcmcquen/react-habitat-poc

**Comment by jennasalau** [comment]
Hi Ryan,

Welcome back! Thanks for your continued support 👍 

I've checked out your code and had a look. Im a bit puzzled because I can replicate your issue following your steps. However, recreating your steps in code and everything works flawlessly!

For example, add this code at the end of your `Manifest.js` file

```
window.mount1 = function() {
    const target = document.createElement('div');
    target.innerHTML = '<div data-component="Cart"></div>';
    window.document.body.appendChild(target);
    window.updateHabitat();
};

window.mount2 = function() {
    const target = document.createElement('div');
    target.innerHTML = '<div\n' +
        '    data-component="ProductCard"\n' +
        '    data-prop-add-to-cart="true"\n' +
        '    data-prop-alt="Teakhaus Edge Grain cutting board"\n' +
        '    data-prop-price="$200.00"\n' +
        '    data-prop-sku="3422086"\n' +
        '></div>';
    window.document.body.appendChild(target);
    window.updateHabitat();
};
```

Then in your browser dev tools console

- Enter command `window.mount1()`. Verify the shopping cart added to the end of the page.
- Enter command `window.mount2()`. Verify the product card added to the end of the page.
- Now click ADD TO CART on the new ProductCard container.
- The cart views update correctly.

Can you please verify.

I have a feeling that editing the HTML in dev tools is doing something screwy with node references. Im just not sure if this is our bug or a bug with Provider in Redux yet.

**Comment by ryanpcmcquen** [comment]
That works for me also, weirdness! A workaround we found is moving the parentheses to be outside the `span` tag. This also works with the dev tools scenario. It feels like a JSX bug to me, but it could also be dev tools related.

**Comment by ryanpcmcquen** [comment]
And here is the fix for reference:
https://github.com/ryanpcmcquen/react-habitat-poc/commit/54b33411f5fb1cfed79f77d9f17e8dc670e30aa4
